### ISSUE TITLE
Syntax highlighting for ATF

### ISSUE THREAD

**Issue by ageorgou** [oracc/nisaba#1]

**Comment by giordano** [comment]
This was mostly done by #4 and #17.  The only thing remaining is to highlight differently the known keywords in `$`-lines, this is just a matter of changing the name of the match
https://github.com/oracc/vscode-language-sample/blob/dbdb4ed0e0be47bfb342d724b6be8123db1b681e/python/generate_syntax_highlightining.py#L62-L63
However see #18 for having to have yet another different colour.

**Comment by raquel-ucl** [comment]
Can be closed as remaining work is described in #18.
