### ISSUE TITLE
Not able to validate or lemmatise: project code not found

### ISSUE THREAD

**Issue by ofeliatweets** [oracc/nisaba#129]
**Describe the problem**
I am not able to validate or lemmatise my ATF files. I get the "project code not found in ATF" error. The files work fine in NAMMU. My colleague is having the same issue.

**To Reproduce**
Basically I open an ATF file, click validate or lemmatise and get the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/120198556/206741049-0648c97b-03d9-45c0-a95a-d605b6ff7cda.png)
![image](https://user-images.githubusercontent.com/120198556/206741349-f04585db-4276-450b-9786-031def36e9f3.png)

**User desktop system (please complete the following information):**
 - OS: Windows
 - Version 10.0.19043

Thanks!!

**Comment by giordano** [comment]
Thanks a lot for the report!  Would it be possible for you to share the file, if it doesn't contain anything non-public?  You can drag and drop it in the comment box below.  I'm wondering if this problem is related to the line-ending of your file.

**Comment by ofeliatweets** [comment]
No problem - it appears github won't allow me to attach it as it is an unsupported type so I save it as a txt - hopefully that works.
[babcityATFtest.txt](https://github.com/oracc/nisaba/files/10196537/babcityATFtest.txt)

**Comment by giordano** [comment]
Yes, the extension is no problem, I can rename it afterwards.  I'll take a look, thanks!

**Comment by ofeliatweets** [comment]
Thank you! Note I get the same error even when there's no lemmas or even when I have just the header lines, not sure if that helps narrow the issue down.

**Comment by giordano** [comment]
Unfortunately I can't reproduce the problem you reported with your file on my machine.  However, it'd be helpful to have one more bit of information: what version of Nisaba are you using?  You can find the number if you go to the list of extensions (press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>t</kbd> or click on the
![image](https://user-images.githubusercontent.com/765740/206769296-6d6053c6-9aef-4c48-aac0-ced5a2940b11.png)
icon on the left sidebar), search for "nisaba" and then click on it.  You should get a page like 
![image](https://user-images.githubusercontent.com/765740/206769543-309f6257-ccf2-4d3b-ad88-e00abb9979eb.png)
for me the version number is 1.3.0.  I'm asking just in case you're somehow using an older version and the code I'm looking at is different than what you're running on your machine.  Thanks!

**Comment by ofeliatweets** [comment]
Sadly I am also running 1.3.0 
My colleague is experiencing the same issues as myself so at least I know it's not only me.

**Comment by giordano** [comment]
@ofeliatweets sorry, another question: what version of Visual Studio Code are you using?  You can find it in the menu Help -> About.

I trust you're experiencing this issue, but I'm having a hard time figuring out what can be the problem with detecting the project name, the code is relatively straightforward, so I'm trying to collect as much information as possible about your configuration.  A colleague just tried to run lemmatisation on your file using Nisaba 1.3.0 + VS Code 1.74.0 + Windows 10 and they could also not reproduce your error :frowning_face:

**Comment by ofeliatweets** [comment]
Wow!!! I think you may have found it. So firstly my line is purple (maybe that's stylistic but just in case, letting you know) and you can see it is LF not CRLF and ATF not Oracc ATF. So after switching from LF to CRLF it seems to work!!! I can't change it to Oracc ATF as that doesn't seem to be an option for me though. I have attached the screenshot of original settings, the settings that seem to work, and options I get for changing ATF.
![image](https://user-images.githubusercontent.com/120198556/207313670-41eb3adf-b63c-4d05-ab3f-99c3b86ac4f6.png)
![image](https://user-images.githubusercontent.com/120198556/207313762-41c94c97-b3d3-4530-9c10-ff3a6971916f.png)
![image](https://user-images.githubusercontent.com/120198556/207314135-8b5557d9-3762-4f5b-bdd0-14eacb22668b.png)
![image](https://user-images.githubusercontent.com/120198556/207314275-8d2caeb6-e0f9-45fe-a957-105f7d67fefb.png)

**Comment by giordano** [comment]
Ok, so the problem was indeed related to the line-ending as I initially thought, but the file you sent over did have CRLF line endings :confused:  I wonder if that was modified by GitHub when you uploaded it, that'd be very unfortunate.

Anyway, so, the problem is that we need to allow for handling LF line endings on Windows as well.  Thanks a lot for getting back, that was very helpful!

**Comment by ofeliatweets** [comment]
Thank you so much!

**Comment by giordano** [comment]
I pushed a fix in #129, including a test to make sure this problem doesn't arise again in the future, but you'll be able to enjoy the fix in the next version of Nisaba, 1.4.0, which I'm aiming to publish by next week.  I'll let you know when that'll be available.   Thanks again for the help!

**Comment by giordano** [comment]
@ofeliatweets today we released v1.4.1 of Nisaba which includes the fix for this issue.  If you go to the list of extensions of VS Code and click on the Nisaba item, you should find an option to update it to the latest release (v1.4.1).  With this, you should finally be able to lemmatise and validate files with both CRLF and LF line ending without problems.  Do let us know if you have any other questions, and thanks again for the help in tracking down the bug!

**Comment by ofeliatweets** [comment]
Hi there! Everything seemed to be working on Friday but there's a new error now when I try to lemmatise or validate: 
An error has occurred: Error during communication with server: Unexpected message from server: /home/oracc/tmp/sop/svGbP3/status not found (-1) The log may contain more details.****
I wonder if it has something to do with the new release? I was getting the error yesterday and still getting it today.

**Comment by giordano** [comment]
Hi, thanks for the report, I can confirm I can also reproduce the error but this kind of problem is outside of our control and is generally due to a problem on the remote Oracc server.

**Comment by ofeliatweets** [comment]
Ah yes, I just checked and Nammu is showing "Couldn't get server logs" error. Hopefully they fix it soon! Thanks!
