### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nisaba#26]
Nammu has a logger and it was really useful specially when we were checking the communication with the server. If we can use whatever logging system VS Code has, that'd be great. Otherwise we should keep our own. 

I realised about this as I was looking into the `request.log` returned by the server validation response, which is useless for the user but can tell us information about the server if something is not going well.

**Comment by giordano** [comment]
For relatively simple needs, [`console.log`](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) may be enough.  After some research I found [`@vscode-logging/logger`](https://www.npmjs.com/package/@vscode-logging/logger), which seems to provide more sophisticated features, including different logging levels, but it doesn't seem to be super popular, so I'm not sure it's the best option out there.

**Comment by ageorgou** [comment]
From a quick look I also can't see an internal VS Code logger that we can use, nor anything in the Node.js standard library.

Apart from the one @giordano mentioned, there are several Javascript/Typescript logging libraries (see e.g. [this list](https://openbase.com/categories/js/best-nodejs-logging-libraries?orderBy=RECOMMENDED&)). The most popular seem to be:
- [winston](https://www.npmjs.com/package/winston)
- [pino](https://github.com/pinojs/pino)
- [Bunyan](https://github.com/trentm/node-bunyan)
- [log4js](https://www.npmjs.com/package/log4js)

There are various tutorials and articles with examples, so trying one or two might not be too hard.

**Comment by ageorgou** [comment]
Opened #33 for discussing what we need and looking into the different options. I suggest we keep this issue for tracking the progress of the actual implementation.
