### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by ageorgou** [oracc/nisaba#56]
Directions for users:
- Download and install (VSCode and extension)
- Setup GUI? (move tabs around, ...)
- How to use:
        - Validation
        - Lemmatisation
        - Preview
- General information (what you can do with Nisaba)

Can look into Nammu docs, especially for the general information.

**Comment by raquel-ucl** [comment]
Some progress done in #71 but we still need to review this to incorporate:

- [ ] New screenshots showing the lemmatisation button
- [ ] How to install section which is blocked by #60
