### ISSUE TITLE
lack of automatic line-wrap?

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nisaba#93]
Is it possible to implement automatic line-wrap in Nisaba? This is the only issue my students and I have encountered in using Nisaba so far - the fact that the ends of long lines extend beyond the window makes it difficult to take in whole text passages at a glance.

**Comment by giordano** [comment]
Thanks for your feedback!  There is on option in Visual Studio Code to enable word wrapping, it should be in the menu `View` -> `Word Wrap`.  This is what I see when I enable this option:

![image](https://user-images.githubusercontent.com/765740/151577220-5c80c1a4-d7c1-4954-b1fb-d291d7a789c8.png)

Is this what you'd like?

**Comment by zarpanitu** [comment]
Perfect! Thank you - sorry I missed this, I am new to Visual Studio Code.

Best wishes
Heather

Heather D. Baker
Assistant Professor, Ancient Near Eastern History
University of Toronto
Department of Near and Middle Eastern Civilizations
4 Bancroft Avenue, 2nd Floor
Toronto
Ontario M5S 1C1
Canada

https://heatherdbaker.hcommons.org


On Jan 28, 2022, 10:46 -0500, Mosè Giordano ***@***.***>, wrote:

Thanks for your feedback! There is on option in Visual Studio Code to enable word wrapping, it should be in the menu View -> Word Wrap. This is what I see when I enable this option:

[image]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F765740%2F151577220-5c80c1a4-d7c1-4954-b1fb-d291d7a789c8.png&data=04%7C01%7Cheather.baker%40utoronto.ca%7Cb655a895c18b4c5ac77808d9e27562ab%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637789816062023925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VnSxvSVqDSGN8ariQrnDUSFX5x5W%2FkxC3n0TYCbi00o%3D&reserved=0>

Is this what you'd like?

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foracc%2Fnisaba%2Fissues%2F93%23issuecomment-1024345056&data=04%7C01%7Cheather.baker%40utoronto.ca%7Cb655a895c18b4c5ac77808d9e27562ab%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637789816062023925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w4MMYhmsePg3RUKDHoLqUKu%2B9%2FV4iLexGpvjL%2FQmd%2Fc%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHAT4ZMKMH72FKQSGR2S4DTUYK26HANCNFSM5NBCIRAQ&data=04%7C01%7Cheather.baker%40utoronto.ca%7Cb655a895c18b4c5ac77808d9e27562ab%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637789816062023925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gJ1xi09rjbk6PS3bA8vwc9SyficZeFv5UG%2BEoq8XcQY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cheather.baker%40utoronto.ca%7Cb655a895c18b4c5ac77808d9e27562ab%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637789816062023925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RqcdvE8M%2B6SpvIgJu4XHPAgSrhTqZV92g8ySfjKMr2w%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cheather.baker%40utoronto.ca%7Cb655a895c18b4c5ac77808d9e27562ab%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637789816062023925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8XM2Oq2rOpbkMceWed9tNNSVSx5VjNsDWasqBmPa8Xo%3D&reserved=0>.

**Comment by giordano** [comment]
In #93 we're looking into the possibility of automatically enabling word wrapping for ATF files, I think it makes sense for this file format.  Thanks again for your feedback, it was very useful!
